feat: caseString to parse strings case-insensitively
GregRos/parjs pull request #99
Opened 2024-01-22 15:35 UTC by xmasoracle

Fixes #91 .

2024-01-22 15:52 UTC, sp3ctum requested changes
All in all, looks good 👍🏻 . Requested some minor changes, details in the diff section.

2024-01-22 15:52 UTC, sp3ctum commented on src/lib/internal/parsers/case-string.ts
> + */
issue: I wonder if this was inserted here by accident or some tool. Parjs is MIT licensed and not affiliated with Oracle as far as I know.

2024-01-22 15:52 UTC, sp3ctum commented on src/lib/internal/parsers/case-string.ts
> +/** */
question: maybe this is not needed. Does it affect formatting somehow?

2024-01-22 15:52 UTC, sp3ctum commented on src/test/unit/standalone/string.spec.ts
> +        const parser = caseString(s);
suggestion: let's change this to have an explicit type annotation. This way it can also act as a test for the expected type.

The expected type is currently correct and defaults to the narrow constant type `"foo"` instead of `string`. However, if someone accidentally breaks that type narrowing feature in the future, an explicit annotation will catch that regression and also catch that bug

```suggestion
        const parser: Parjser<"foo"> = caseString("foo");
```

2024-01-22 15:52 UTC, sp3ctum commented on src/test/unit/standalone/string.spec.ts
> +            it(`success${i}`, () => {
nitpick(optional): I would prefer "succeeds in parsing ..." or "can parse ...", but this is not a big issue.

2024-01-22 15:52 UTC, sp3ctum commented on src/test/unit/standalone/string.spec.ts
> +        });
nitpick(optional): same here, could be "fails to parse ..." or something like that.

2024-01-22 15:56 UTC, xmasoracle commented on src/lib/internal/parsers/case-string.ts
> + */
Not an accident: this is a requirement by my employer that I mark code I develop on my work time with this notice...

2024-01-22 15:57 UTC, xmasoracle commented on src/test/unit/standalone/string.spec.ts
> +            it(`success${i}`, () => {
I tried to follow the format of other tests. Will update.

2024-01-22 17:35 UTC, sp3ctum commented on src/lib/internal/parsers/case-string.ts
> + */
Ok, I understand that your employer has paid for you to contribute this change, and as part of that agreement they (meaning Oracle) want to be listed as the copyright holder for those changes.

# some research

I have never been in this situation before, but I did some research (meaning: I googled something for an hour) and here's some of my thoughts:
- overall, I understood that each contributor to an open source project is, automatically and by default, the copyright holder of the changes they have contributed, whether listed explicitly or not
- listing parties that hold copyrights to parts of the project does not change the project's licensing (although I don't understand why as intuitively it feels like they are in conflict, but I'm not a lawyer)
- I don't know if any specific country's laws are used by default. From what I know, this project has contributors in many different countries.

# potential headaches

While I don't _think_ this has any impact on the legal status or licensing of the project, I think we need to be careful when handling the copyright notice:
- if the code is changed a little, it should be left in tact
- if the code is removed, the license should be removed too
- if the code is refactored and somehow split into two, should the license now be in two files instead of one?

---

# summary and a proposition
Copyright related things are not my area of expertise. As this is obviously not the focus of the project either, I wonder if it could be easier to simply list all contributors in a central place?

As an example, here is an automated solution that I think looks nice: https://github.com/all-contributors/all-contributors

Also summoning @GregRos, I think you should make this choice as you are the owner of the project.

2024-02-09 22:06 UTC, GregRos commented
So... yeah, I've tried looking it up and I have no idea what this means.

I've [called in the cavalry](https://opensource.stackexchange.com/questions/14587/someone-wants-to-contribute-code-with-a-copyright-notice-should-i-be-concerned)

2024-02-10 13:35 UTC, sp3ctum commented
Great idea to ask for opinions.

Based on the feedback in that question, it sounds to me like that idea about the listing of contributors does not necessarily remove the need for dealing with the licenses in the source files.

We can just think about adding the list of contributors separately, then 🙂

2024-02-11 20:16 UTC, GregRos commented
It turns out the pipeline failed, so I decided to first merge the refactor #102 since it also fixes the pipeline. I refactored this PR to match at #103.

I'm closing this now. thank you!

2024-02-11 20:16 UTC, closed without merging